development:
  dialect: postgres
  datasource: host=localhost port=5432 user=ryan password=postgres dbname=chapi sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=localhost port=5432 user=ryan password=postgres dbname=chapi sslmode=disable
  dir: migrations
  table: migrations

staging:
  dialect: postgres
  datasource: host=localhost port=5432 user=ryan password=postgres dbname=chapi sslmode=disable
  dir: migrations
  table: migrations